### PR TITLE
docs(dashboard): add dashboard README

### LINKED ISSUE #60: Dashboard README
- Some screenshots on certain flows (creating/updating vulns)
- Libraries used??
- Stuffs i guess

### PR DESCRIPTION
**Pull request by fionaochee**
Add dashboard README.

Resolves #60

### CODE REVIEW

**Review by stevenp2 — COMMENTED** [review]
lgtm

**Review by stevenp2 — APPROVED** [review]
LGTM!

**Review by axieax — APPROVED** [review]
image

**Review by axieax — APPROVED** [review]
:lgtm:

**Pull request merged**
